(function () {
  "use strict";

  /*
    Generated by scripts/generate-site.mjs.
    Keep checkout/API keys out of this file. This file is public frontend code.
    Checkout is created dynamically through /api/checkout; keep Stripe secrets out of this file.
    Product segmentation: industry | quarter/year | access | cityInclusion.
  */
  window.SherlockCatalog = {
  "supportEmail": "hello@sherlockreports.com",
  "defaultReportSlug": "landscaping",
  "statuses": {
    "available": {
      "label": "Available now",
      "libraryLabel": "Active",
      "cta": "Get the report",
      "checkoutCta": "Get the report",
      "schemaAvailability": "https://schema.org/InStock",
      "buyerNote": "You'll get an email confirmation right after checkout. If the full report is still being finalized, we'll tell you exactly when to expect it."
    },
    "presell": {
      "label": "Presell",
      "libraryLabel": "Presell",
      "cta": "Reserve the report",
      "checkoutCta": "Reserve the report",
      "schemaAvailability": "https://schema.org/PreOrder",
      "buyerNote": "Reserve now and you'll get an email confirmation today, plus your full report the moment it's published."
    },
    "waitlist": {
      "label": "Waitlist",
      "libraryLabel": "Waitlist",
      "cta": "Join the waitlist",
      "checkoutCta": "Join the waitlist",
      "schemaAvailability": "https://schema.org/PreOrder",
      "buyerNote": "Join the waitlist to help prioritize this report and get the launch notice."
    }
  },
  "plans": {
    "single": {
      "name": "Standard Report",
      "price": "$497",
      "unit": "",
      "cadence": "one-time",
      "checkoutUrl": "",
      "description": "Full national industry report, recommendations, and email confirmation."
    },
    "quarterly": {
      "name": "Quarterly + Coaching",
      "price": "$2,000",
      "unit": "/yr",
      "cadence": "annual",
      "checkoutUrl": "",
      "description": "Four quarterly updates plus four one-on-one coaching calls."
    },
    "all": {
      "name": "All-Access Pass",
      "price": "$2,997",
      "unit": "",
      "cadence": "one-time",
      "checkoutUrl": "",
      "description": "Every Sherlock industry report, current and future releases."
    }
  },
  "reports": {
    "landscaping": {
      "name": "Landscaping",
      "status": "available",
      "category": "home-services",
      "page": "landscaping-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/lbv8qW",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.landscaping",
        "waitlistEvent": "sherlock.report.waitlist.landscaping",
        "tags": [
          "industry:landscaping",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "https://payhip.com/b/zPJah",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "landscaping-2026-q2-full-national",
          "plan": "single",
          "industry": "Landscaping",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Landscaping Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "https://payhip.com/b/zPJah",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "landscaping-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Landscaping",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Landscaping Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "https://payhip.com/b/zPJah",
        "quarterly": ""
      }
    },
    "roofing": {
      "name": "Roofing",
      "status": "available",
      "category": "home-services",
      "page": "roofing-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/RGkqdJ",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.roofing",
        "waitlistEvent": "sherlock.report.waitlist.roofing",
        "tags": [
          "industry:roofing",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "roofing-2026-q2-full-national",
          "plan": "single",
          "industry": "Roofing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Roofing Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "roofing-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Roofing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Roofing Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "dental": {
      "name": "Dental",
      "status": "presell",
      "category": "healthcare",
      "page": "dental-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/Gx5OKo",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.dental",
        "waitlistEvent": "sherlock.report.waitlist.dental",
        "tags": [
          "industry:dental",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "dental-2026-q2-full-national",
          "plan": "single",
          "industry": "Dental",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Dental Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "dental-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Dental",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Dental Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "dermatology": {
      "name": "Dermatology",
      "status": "presell",
      "category": "healthcare",
      "page": "dermatology-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/ODkxl8",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.dermatology",
        "waitlistEvent": "sherlock.report.waitlist.dermatology",
        "tags": [
          "industry:dermatology",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "dermatology-2026-q2-full-national",
          "plan": "single",
          "industry": "Dermatology",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Dermatology Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "dermatology-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Dermatology",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Dermatology Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "hvac": {
      "name": "HVAC",
      "status": "available",
      "category": "home-services",
      "page": "hvac-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/VLDWjv",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.hvac",
        "waitlistEvent": "sherlock.report.waitlist.hvac",
        "tags": [
          "industry:hvac",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "hvac-2026-q2-full-national",
          "plan": "single",
          "industry": "HVAC",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "HVAC Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "hvac-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "HVAC",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "HVAC Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "pest-control": {
      "name": "Pest Control",
      "status": "available",
      "category": "home-services",
      "page": "pest-control-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/PdkZDb",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.pest-control",
        "waitlistEvent": "sherlock.report.waitlist.pest-control",
        "tags": [
          "industry:pest-control",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "pest-control-2026-q2-full-national",
          "plan": "single",
          "industry": "Pest Control",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Pest Control Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "pest-control-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Pest Control",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Pest Control Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "plumbing": {
      "name": "Plumbing",
      "status": "presell",
      "category": "home-services",
      "page": "plumbing-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/EkMo5N",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.plumbing",
        "waitlistEvent": "sherlock.report.waitlist.plumbing",
        "tags": [
          "industry:plumbing",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "plumbing-2026-q2-full-national",
          "plan": "single",
          "industry": "Plumbing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Plumbing Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "plumbing-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Plumbing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Plumbing Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "electrical": {
      "name": "Electrical",
      "status": "presell",
      "category": "home-services",
      "page": "electrical-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/rjv8Bv",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.electrical",
        "waitlistEvent": "sherlock.report.waitlist.electrical",
        "tags": [
          "industry:electrical",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "electrical-2026-q2-full-national",
          "plan": "single",
          "industry": "Electrical",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Electrical Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "electrical-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Electrical",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Electrical Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "med-spa": {
      "name": "Med Spa",
      "status": "presell",
      "category": "healthcare",
      "page": "med-spa-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/44zlBO",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.med-spa",
        "waitlistEvent": "sherlock.report.waitlist.med-spa",
        "tags": [
          "industry:med-spa",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "med-spa-2026-q2-full-national",
          "plan": "single",
          "industry": "Med Spa",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Med Spa Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "med-spa-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Med Spa",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Med Spa Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "auto-repair": {
      "name": "Auto Repair",
      "status": "presell",
      "category": "automotive",
      "page": "auto-repair-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/jav8bE",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "dynamic",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.auto-repair",
        "waitlistEvent": "sherlock.report.waitlist.auto-repair",
        "tags": [
          "industry:auto-repair",
          "category:automotive"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "auto-repair-2026-q2-full-national",
          "plan": "single",
          "industry": "Auto Repair",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Auto Repair Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "auto-repair-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Auto Repair",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Auto Repair Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "garage-door": {
      "name": "Garage Door",
      "status": "waitlist",
      "category": "home-services",
      "page": "garage-door-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/WO1a8J",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.garage-door",
        "waitlistEvent": "sherlock.report.waitlist.garage-door",
        "tags": [
          "industry:garage-door",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "garage-door-2026-q2-full-national",
          "plan": "single",
          "industry": "Garage Door",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Garage Door Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "garage-door-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Garage Door",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Garage Door Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "pool-service": {
      "name": "Pool Service",
      "status": "waitlist",
      "category": "home-services",
      "page": "pool-service-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/aQvp29",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.pool-service",
        "waitlistEvent": "sherlock.report.waitlist.pool-service",
        "tags": [
          "industry:pool-service",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "pool-service-2026-q2-full-national",
          "plan": "single",
          "industry": "Pool Service",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Pool Service Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "pool-service-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Pool Service",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Pool Service Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "lawn-care": {
      "name": "Lawn Care",
      "status": "waitlist",
      "category": "home-services",
      "page": "lawn-care-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/68M6Ze",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.lawn-care",
        "waitlistEvent": "sherlock.report.waitlist.lawn-care",
        "tags": [
          "industry:lawn-care",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "lawn-care-2026-q2-full-national",
          "plan": "single",
          "industry": "Lawn Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Lawn Care Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "lawn-care-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Lawn Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Lawn Care Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "tree-care": {
      "name": "Tree Care",
      "status": "waitlist",
      "category": "home-services",
      "page": "tree-care-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/7RM7NL",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.tree-care",
        "waitlistEvent": "sherlock.report.waitlist.tree-care",
        "tags": [
          "industry:tree-care",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "tree-care-2026-q2-full-national",
          "plan": "single",
          "industry": "Tree Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Tree Care Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "tree-care-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Tree Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Tree Care Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "home-cleaning": {
      "name": "Home Cleaning",
      "status": "waitlist",
      "category": "home-services",
      "page": "home-cleaning-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/b5v1We",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.home-cleaning",
        "waitlistEvent": "sherlock.report.waitlist.home-cleaning",
        "tags": [
          "industry:home-cleaning",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "home-cleaning-2026-q2-full-national",
          "plan": "single",
          "industry": "Home Cleaning",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Home Cleaning Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "home-cleaning-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Home Cleaning",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Home Cleaning Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "carpet-cleaning": {
      "name": "Carpet Cleaning",
      "status": "waitlist",
      "category": "home-services",
      "page": "carpet-cleaning-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/A7yMBB",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.carpet-cleaning",
        "waitlistEvent": "sherlock.report.waitlist.carpet-cleaning",
        "tags": [
          "industry:carpet-cleaning",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "carpet-cleaning-2026-q2-full-national",
          "plan": "single",
          "industry": "Carpet Cleaning",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Carpet Cleaning Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "carpet-cleaning-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Carpet Cleaning",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Carpet Cleaning Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "restoration": {
      "name": "Restoration",
      "status": "waitlist",
      "category": "home-services",
      "page": "restoration-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/Bz0Jx7",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.restoration",
        "waitlistEvent": "sherlock.report.waitlist.restoration",
        "tags": [
          "industry:restoration",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "restoration-2026-q2-full-national",
          "plan": "single",
          "industry": "Restoration",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Restoration Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "restoration-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Restoration",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Restoration Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "painting": {
      "name": "Painting",
      "status": "waitlist",
      "category": "home-services",
      "page": "painting-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/kdv8N6",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.painting",
        "waitlistEvent": "sherlock.report.waitlist.painting",
        "tags": [
          "industry:painting",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "painting-2026-q2-full-national",
          "plan": "single",
          "industry": "Painting",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Painting Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "painting-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Painting",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Painting Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "flooring": {
      "name": "Flooring",
      "status": "waitlist",
      "category": "home-services",
      "page": "flooring-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/vGK8PA",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.flooring",
        "waitlistEvent": "sherlock.report.waitlist.flooring",
        "tags": [
          "industry:flooring",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "flooring-2026-q2-full-national",
          "plan": "single",
          "industry": "Flooring",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Flooring Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "flooring-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Flooring",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Flooring Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "windows-and-doors": {
      "name": "Windows and Doors",
      "status": "waitlist",
      "category": "home-services",
      "page": "windows-and-doors-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/KYkrVM",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.windows-and-doors",
        "waitlistEvent": "sherlock.report.waitlist.windows-and-doors",
        "tags": [
          "industry:windows-and-doors",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "windows-and-doors-2026-q2-full-national",
          "plan": "single",
          "industry": "Windows and Doors",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Windows and Doors Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "windows-and-doors-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Windows and Doors",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Windows and Doors Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "kitchen-and-bath-remodeling": {
      "name": "Kitchen and Bath Remodeling",
      "status": "waitlist",
      "category": "home-services",
      "page": "kitchen-and-bath-remodeling-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/LZk4PG",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.kitchen-and-bath-remodeling",
        "waitlistEvent": "sherlock.report.waitlist.kitchen-and-bath-remodeling",
        "tags": [
          "industry:kitchen-and-bath-remodeling",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "kitchen-and-bath-remodeling-2026-q2-full-national",
          "plan": "single",
          "industry": "Kitchen and Bath Remodeling",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Kitchen and Bath Remodeling Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "kitchen-and-bath-remodeling-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Kitchen and Bath Remodeling",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Kitchen and Bath Remodeling Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "general-contracting": {
      "name": "General Contracting",
      "status": "waitlist",
      "category": "home-services",
      "page": "general-contracting-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/pbvYDV",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.general-contracting",
        "waitlistEvent": "sherlock.report.waitlist.general-contracting",
        "tags": [
          "industry:general-contracting",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "general-contracting-2026-q2-full-national",
          "plan": "single",
          "industry": "General Contracting",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "General Contracting Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "general-contracting-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "General Contracting",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "General Contracting Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "solar-installation": {
      "name": "Solar Installation",
      "status": "waitlist",
      "category": "home-services",
      "page": "solar-installation-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/1A6Q9M",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.solar-installation",
        "waitlistEvent": "sherlock.report.waitlist.solar-installation",
        "tags": [
          "industry:solar-installation",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "solar-installation-2026-q2-full-national",
          "plan": "single",
          "industry": "Solar Installation",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Solar Installation Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "solar-installation-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Solar Installation",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Solar Installation Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "security-systems": {
      "name": "Security Systems",
      "status": "waitlist",
      "category": "home-services",
      "page": "security-systems-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/MeMjEY",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.security-systems",
        "waitlistEvent": "sherlock.report.waitlist.security-systems",
        "tags": [
          "industry:security-systems",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "security-systems-2026-q2-full-national",
          "plan": "single",
          "industry": "Security Systems",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Security Systems Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "security-systems-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Security Systems",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Security Systems Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "moving": {
      "name": "Moving",
      "status": "waitlist",
      "category": "home-services",
      "page": "moving-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/J9MEOJ",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.moving",
        "waitlistEvent": "sherlock.report.waitlist.moving",
        "tags": [
          "industry:moving",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "moving-2026-q2-full-national",
          "plan": "single",
          "industry": "Moving",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Moving Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "moving-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Moving",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Moving Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "self-storage": {
      "name": "Self Storage",
      "status": "waitlist",
      "category": "local-services",
      "page": "self-storage-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/gDv89N",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.self-storage",
        "waitlistEvent": "sherlock.report.waitlist.self-storage",
        "tags": [
          "industry:self-storage",
          "category:local-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "self-storage-2026-q2-full-national",
          "plan": "single",
          "industry": "Self Storage",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Self Storage Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "self-storage-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Self Storage",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Self Storage Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "junk-removal": {
      "name": "Junk Removal",
      "status": "waitlist",
      "category": "home-services",
      "page": "junk-removal-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/yPz8J0",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.junk-removal",
        "waitlistEvent": "sherlock.report.waitlist.junk-removal",
        "tags": [
          "industry:junk-removal",
          "category:home-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "junk-removal-2026-q2-full-national",
          "plan": "single",
          "industry": "Junk Removal",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Junk Removal Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "junk-removal-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Junk Removal",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Junk Removal Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "car-wash-and-detailing": {
      "name": "Car Wash and Detailing",
      "status": "waitlist",
      "category": "automotive",
      "page": "car-wash-and-detailing-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/Xxz64O",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.car-wash-and-detailing",
        "waitlistEvent": "sherlock.report.waitlist.car-wash-and-detailing",
        "tags": [
          "industry:car-wash-and-detailing",
          "category:automotive"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "car-wash-and-detailing-2026-q2-full-national",
          "plan": "single",
          "industry": "Car Wash and Detailing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Car Wash and Detailing Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "car-wash-and-detailing-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Car Wash and Detailing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Car Wash and Detailing Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "towing": {
      "name": "Towing",
      "status": "waitlist",
      "category": "automotive",
      "page": "towing-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/81MbZA",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.towing",
        "waitlistEvent": "sherlock.report.waitlist.towing",
        "tags": [
          "industry:towing",
          "category:automotive"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "towing-2026-q2-full-national",
          "plan": "single",
          "industry": "Towing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Towing Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "towing-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Towing",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Towing Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "veterinary": {
      "name": "Veterinary",
      "status": "waitlist",
      "category": "healthcare",
      "page": "veterinary-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/0QaqeZ",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.veterinary",
        "waitlistEvent": "sherlock.report.waitlist.veterinary",
        "tags": [
          "industry:veterinary",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "veterinary-2026-q2-full-national",
          "plan": "single",
          "industry": "Veterinary",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Veterinary Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "veterinary-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Veterinary",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Veterinary Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "physical-therapy": {
      "name": "Physical Therapy",
      "status": "waitlist",
      "category": "healthcare",
      "page": "physical-therapy-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/zxL871",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.physical-therapy",
        "waitlistEvent": "sherlock.report.waitlist.physical-therapy",
        "tags": [
          "industry:physical-therapy",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "physical-therapy-2026-q2-full-national",
          "plan": "single",
          "industry": "Physical Therapy",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Physical Therapy Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "physical-therapy-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Physical Therapy",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Physical Therapy Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "chiropractic": {
      "name": "Chiropractic",
      "status": "waitlist",
      "category": "healthcare",
      "page": "chiropractic-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/5BMaZM",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.chiropractic",
        "waitlistEvent": "sherlock.report.waitlist.chiropractic",
        "tags": [
          "industry:chiropractic",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "chiropractic-2026-q2-full-national",
          "plan": "single",
          "industry": "Chiropractic",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Chiropractic Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "chiropractic-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Chiropractic",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Chiropractic Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "senior-home-care": {
      "name": "Senior Home Care",
      "status": "waitlist",
      "category": "healthcare",
      "page": "senior-home-care-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/dWvJ9z",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.senior-home-care",
        "waitlistEvent": "sherlock.report.waitlist.senior-home-care",
        "tags": [
          "industry:senior-home-care",
          "category:healthcare"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "senior-home-care-2026-q2-full-national",
          "plan": "single",
          "industry": "Senior Home Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Senior Home Care Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "senior-home-care-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Senior Home Care",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Senior Home Care Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "childcare": {
      "name": "Childcare",
      "status": "waitlist",
      "category": "education",
      "page": "childcare-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/Y5k74q",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.childcare",
        "waitlistEvent": "sherlock.report.waitlist.childcare",
        "tags": [
          "industry:childcare",
          "category:education"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "childcare-2026-q2-full-national",
          "plan": "single",
          "industry": "Childcare",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Childcare Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "childcare-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Childcare",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Childcare Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "fitness-gyms": {
      "name": "Fitness Gyms",
      "status": "waitlist",
      "category": "local-services",
      "page": "fitness-gyms-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/D4MR7b",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.fitness-gyms",
        "waitlistEvent": "sherlock.report.waitlist.fitness-gyms",
        "tags": [
          "industry:fitness-gyms",
          "category:local-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "fitness-gyms-2026-q2-full-national",
          "plan": "single",
          "industry": "Fitness Gyms",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Fitness Gyms Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "fitness-gyms-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Fitness Gyms",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Fitness Gyms Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "restaurants": {
      "name": "Restaurants",
      "status": "waitlist",
      "category": "hospitality",
      "page": "restaurants-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/lbv865",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.restaurants",
        "waitlistEvent": "sherlock.report.waitlist.restaurants",
        "tags": [
          "industry:restaurants",
          "category:hospitality"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "restaurants-2026-q2-full-national",
          "plan": "single",
          "industry": "Restaurants",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Restaurants Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "restaurants-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Restaurants",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Restaurants Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "coffee-shops": {
      "name": "Coffee Shops",
      "status": "waitlist",
      "category": "hospitality",
      "page": "coffee-shops-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/RGkqDl",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.coffee-shops",
        "waitlistEvent": "sherlock.report.waitlist.coffee-shops",
        "tags": [
          "industry:coffee-shops",
          "category:hospitality"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "coffee-shops-2026-q2-full-national",
          "plan": "single",
          "industry": "Coffee Shops",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Coffee Shops Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "coffee-shops-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Coffee Shops",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Coffee Shops Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "breweries": {
      "name": "Breweries",
      "status": "waitlist",
      "category": "hospitality",
      "page": "breweries-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/obv821",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.breweries",
        "waitlistEvent": "sherlock.report.waitlist.breweries",
        "tags": [
          "industry:breweries",
          "category:hospitality"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "breweries-2026-q2-full-national",
          "plan": "single",
          "industry": "Breweries",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Breweries Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "breweries-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Breweries",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Breweries Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "hotels": {
      "name": "Hotels",
      "status": "waitlist",
      "category": "hospitality",
      "page": "hotels-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/Gx5ORj",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.hotels",
        "waitlistEvent": "sherlock.report.waitlist.hotels",
        "tags": [
          "industry:hotels",
          "category:hospitality"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "hotels-2026-q2-full-national",
          "plan": "single",
          "industry": "Hotels",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Hotels Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "hotels-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Hotels",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Hotels Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "event-venues": {
      "name": "Event Venues",
      "status": "waitlist",
      "category": "hospitality",
      "page": "event-venues-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/ODkx7K",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.event-venues",
        "waitlistEvent": "sherlock.report.waitlist.event-venues",
        "tags": [
          "industry:event-venues",
          "category:hospitality"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "event-venues-2026-q2-full-national",
          "plan": "single",
          "industry": "Event Venues",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Event Venues Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "event-venues-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Event Venues",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Event Venues Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "property-management": {
      "name": "Property Management",
      "status": "waitlist",
      "category": "real-estate-finance",
      "page": "property-management-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/VLDWza",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.property-management",
        "waitlistEvent": "sherlock.report.waitlist.property-management",
        "tags": [
          "industry:property-management",
          "category:real-estate-finance"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "property-management-2026-q2-full-national",
          "plan": "single",
          "industry": "Property Management",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Property Management Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "property-management-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Property Management",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Property Management Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "real-estate-brokerages": {
      "name": "Real Estate Brokerages",
      "status": "waitlist",
      "category": "real-estate-finance",
      "page": "real-estate-brokerages-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/PdkZzQ",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.real-estate-brokerages",
        "waitlistEvent": "sherlock.report.waitlist.real-estate-brokerages",
        "tags": [
          "industry:real-estate-brokerages",
          "category:real-estate-finance"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "real-estate-brokerages-2026-q2-full-national",
          "plan": "single",
          "industry": "Real Estate Brokerages",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Real Estate Brokerages Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "real-estate-brokerages-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Real Estate Brokerages",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Real Estate Brokerages Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "mortgage-brokers": {
      "name": "Mortgage Brokers",
      "status": "waitlist",
      "category": "real-estate-finance",
      "page": "mortgage-brokers-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/EkMoxo",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.mortgage-brokers",
        "waitlistEvent": "sherlock.report.waitlist.mortgage-brokers",
        "tags": [
          "industry:mortgage-brokers",
          "category:real-estate-finance"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "mortgage-brokers-2026-q2-full-national",
          "plan": "single",
          "industry": "Mortgage Brokers",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Mortgage Brokers Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "mortgage-brokers-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Mortgage Brokers",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Mortgage Brokers Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "insurance-agencies": {
      "name": "Insurance Agencies",
      "status": "waitlist",
      "category": "professional-services",
      "page": "insurance-agencies-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/rjv8oM",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.insurance-agencies",
        "waitlistEvent": "sherlock.report.waitlist.insurance-agencies",
        "tags": [
          "industry:insurance-agencies",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "insurance-agencies-2026-q2-full-national",
          "plan": "single",
          "industry": "Insurance Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Insurance Agencies Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "insurance-agencies-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Insurance Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Insurance Agencies Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "accounting-and-tax": {
      "name": "Accounting and Tax",
      "status": "waitlist",
      "category": "professional-services",
      "page": "accounting-and-tax-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/44zlKb",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.accounting-and-tax",
        "waitlistEvent": "sherlock.report.waitlist.accounting-and-tax",
        "tags": [
          "industry:accounting-and-tax",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "accounting-and-tax-2026-q2-full-national",
          "plan": "single",
          "industry": "Accounting and Tax",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Accounting and Tax Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "accounting-and-tax-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Accounting and Tax",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Accounting and Tax Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "legal-services": {
      "name": "Legal Services",
      "status": "waitlist",
      "category": "professional-services",
      "page": "legal-services-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/jav8lR",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.legal-services",
        "waitlistEvent": "sherlock.report.waitlist.legal-services",
        "tags": [
          "industry:legal-services",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "legal-services-2026-q2-full-national",
          "plan": "single",
          "industry": "Legal Services",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Legal Services Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "legal-services-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Legal Services",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Legal Services Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "it-managed-services": {
      "name": "IT Managed Services",
      "status": "waitlist",
      "category": "professional-services",
      "page": "it-managed-services-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/2E79Kp",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.it-managed-services",
        "waitlistEvent": "sherlock.report.waitlist.it-managed-services",
        "tags": [
          "industry:it-managed-services",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "it-managed-services-2026-q2-full-national",
          "plan": "single",
          "industry": "IT Managed Services",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "IT Managed Services Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "it-managed-services-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "IT Managed Services",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "IT Managed Services Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "digital-marketing-agencies": {
      "name": "Digital Marketing Agencies",
      "status": "waitlist",
      "category": "professional-services",
      "page": "digital-marketing-agencies-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/xXv8JG",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.digital-marketing-agencies",
        "waitlistEvent": "sherlock.report.waitlist.digital-marketing-agencies",
        "tags": [
          "industry:digital-marketing-agencies",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "digital-marketing-agencies-2026-q2-full-national",
          "plan": "single",
          "industry": "Digital Marketing Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Digital Marketing Agencies Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "digital-marketing-agencies-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Digital Marketing Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Digital Marketing Agencies Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "staffing-agencies": {
      "name": "Staffing Agencies",
      "status": "waitlist",
      "category": "professional-services",
      "page": "staffing-agencies-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/RGkqDp",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.staffing-agencies",
        "waitlistEvent": "sherlock.report.waitlist.staffing-agencies",
        "tags": [
          "industry:staffing-agencies",
          "category:professional-services"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "staffing-agencies-2026-q2-full-national",
          "plan": "single",
          "industry": "Staffing Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Staffing Agencies Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "staffing-agencies-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Staffing Agencies",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Staffing Agencies Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    },
    "private-schools-and-tutoring": {
      "name": "Private Schools and Tutoring",
      "status": "waitlist",
      "category": "education",
      "page": "private-schools-and-tutoring-report.html",
      "samplePage": "sample.html",
      "tallyUrl": "https://tally.so/r/obv82X",
      "sampleAsset": "/assets/sample-landscaping-report.pdf",
      "fullReportAsset": "",
      "readiness": {
        "samplePdf": "ready",
        "fullPdf": "missing",
        "checkout": "waitlist",
        "emailDelivery": "cloudflare-email",
        "audit": "template-passed"
      },
      "email": {
        "purchaseEvent": "sherlock.report.purchase.private-schools-and-tutoring",
        "waitlistEvent": "sherlock.report.waitlist.private-schools-and-tutoring",
        "tags": [
          "industry:private-schools-and-tutoring",
          "category:education"
        ]
      },
      "stripe": {
        "paymentLink": "",
        "productId": "",
        "priceId": ""
      },
      "products": [
        {
          "key": "private-schools-and-tutoring-2026-q2-full-national",
          "plan": "single",
          "industry": "Private Schools and Tutoring",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Private Schools and Tutoring Industry Report, Q2 2026, Full National PDF",
          "checkoutUrl": "",
          "stripeProductId": "",
          "stripePriceId": ""
        },
        {
          "key": "private-schools-and-tutoring-2026-q2-full-quarterly",
          "plan": "quarterly",
          "industry": "Private Schools and Tutoring",
          "quarter": "Q2",
          "year": 2026,
          "access": "full",
          "cityInclusion": "national",
          "title": "Private Schools and Tutoring Quarterly Intelligence, Q2 2026",
          "checkoutUrl": ""
        }
      ],
      "checkout": {
        "single": "",
        "quarterly": ""
      }
    }
  }
};
})();
